const express = require('express')
const bodyparser = require('body-parser')
const fileUpload = require('express-fileupload')
const fileprocessor = require('./FileProcessor')
const loginsignup =require('./login-signup')
const path = require('path')
require('dotenv').config()
const cors = require('cors')
const corsoptions ={
    origin:'*',
    optionsSuccessStatus:200
}
const server = express()
server.use(cors(corsoptions))
const imageserver= express()
server.use(bodyparser.urlencoded({extended: false}))
server.use(bodyparser.json())
server.use(fileUpload())
server.use('/resource',express.static(path.join(__dirname,'static')))
imageserver.use(cors(corsoptions))
imageserver.use('/images',express.static(path.join(__dirname,'serverimages')))

server.get('/loginpage',(req,res)=>{
    res.sendFile(path.join(__dirname,'static','login','index.html'))})
server.get('/mainpage',(req,res)=>{
    res.sendFile(path.join(__dirname,'static','app','index.html'))
})
server.get('/getspace',fileprocessor.getspace)
server.post('/uploadfile',fileprocessor.uploadFile)
server.post('/uploadimage',fileprocessor.uploadImage)
server.get('/loadfile',fileprocessor.loadFile)
server.get('/loadimage',fileprocessor.loadImage)
server.get('/listallfiles',fileprocessor.listAllFiles)
server.delete('/deletefile',fileprocessor.deleteFile)
server.delete('/deleteimage',fileprocessor.deleteImage)
server.put('/updatefilename',fileprocessor.updateFileName)
server.put('/updateimagename',fileprocessor.updateImageName)
server.get('/login',loginsignup.userLogin)
server.post('/signup',loginsignup.userSignup)
server.get('/logout',loginsignup.userlogout)
server.post('/createfolder',fileprocessor.createFolder)
server.delete('/deletefolder',fileprocessor.deleteFolder)
server.get('/search',fileprocessor.search)
server.post('/createfile',fileprocessor.createfile)
server.get('/getfav',fileprocessor.getfav)
server.post('/addfav',fileprocessor.addfav)
server.post('/createcollection',fileprocessor.createcollection)
server.get('/getcollection',fileprocessor.getcollection)
server.post('/transfer',fileprocessor.transfer)
server.put('/updatefoldername',fileprocessor.updatefoldername)
server.post('/addtocollection',fileprocessor.addtocollection)
server.get('/listcollection',fileprocessor.listcollection)
server.get('/reloadwithfilter',fileprocessor.reloadwithfilter)
server.post('/sharefile',fileprocessor.sharefile)
server.get('/getsharefile',fileprocessor.getsharefile)
server.post('/addpeople',fileprocessor.addpeople)
server.get('/getpeople',fileprocessor.getpeople)
server.delete('/removepeople',fileprocessor.removepeople)
server.post('/savefile',fileprocessor.savefile)
server.put('/edituser',loginsignup.edituser)
server.get('/listbinfiles',fileprocessor.listBinFiles)
server.post('/restorefile',fileprocessor.restorefile)
server.get('/download',fileprocessor.download)
server.get('/getfilesshared',fileprocessor.getfilesshared)
server.post('/stopsharing',fileprocessor.stopsharing)
server.post('/removefav',fileprocessor.removefav)
server.get('/spaceanalysis',fileprocessor.spaceanalysis)
server.post('/removecol',fileprocessor.removecol)
server.post('/removefromcol',fileprocessor.removefromcol)
imageserver.get('/images/:token/:imagename',(req,res)=>{
    res.sendFile(path.join(__dirname,'serverimages',req.params.token,req.params.imagename))
})

server.listen(process.env.APP_PORT,()=>{
    console.log('we are live')
})
imageserver.listen(process.env.IMG_PORT,()=>{
    console.log('imagserver live')
})
